### ISSUE TITLE
[BUG] Discrepancies observed between subprocess and simu mode with variancce_method=bootstrap

### ISSUE THREAD

**Issue by jeandut** [owkin/fedeca#26]
Using below test config with newton raphson strategy we observe discrepancies between simu and non simu mode leading in the remote/subprocess mode to instabilities in the hessian raising errors and in the simu mode to no error at all:

```
name: "Real-world experiments"

# initial_seed is used to generate seed for each run
initial_seed: 42

data:
  ndim: 10
  cate: 0.7
  scale_t: 10.0
  shape_t: 3.0
  propensity: "linear"
  standardize_features: False

defaults:
  - /model@models.IPTW: pooled_iptw
  - /model@models.FedECA: fl_iptw
  - _self_

models:
  IPTW:
    effect: "ATE"
    cox_fit_kwargs:
      robust: False
  FedECA:
    ndim: 10
    num_rounds_list: [50, 50]

# config fit FedECA
fit_fedeca:
  n_clients: 2
  variance_method: naive
  split_method: "split_control_over_centers"
  split_method_kwargs: {"treatment_info": "treatment_allocation"}
  data_path: "./tmp"
  # We start on the second url the first is reserved for the server
  urls: [urls]
  server_org_id: 'Org3MSP'

models_common:
  treated_col: "treatment_allocation"
  event_col: "event"
  duration_col: "time"

parameters:
  n_samples: 1_000
  n_reps: 1

hydra:
  sweep:
    dir: "real-world"
  sweeper:
    params:
      # 9 will not be kept but used as a warm-up for the server
      ++fit_fedeca.n_clients: 2
      ++fit_fedeca.backend_type: simu, subprocess #, remote
      ++fit_fedeca.variance_method: bootstrap
```
